### ISSUE TITLE
Clipboard management enhancements

### ISSUE THREAD

**Issue by Darrick255** [Darrick255/AppsKeyAHK#14]
Need a better way to manage the history.

- [ ] #15 View History (gui or some method of browsing)
- [ ] #16  Delete clipboard entry and shift all back.
- [ ] #17 Change length of tooltip at will. (link to repeat timer maybe?)
- [ ] #18 Pre-Save Clipboard file before onexit as app hangs while writing a large history
